package org.meridor.perspective.agent;

public enum OperationType {
    
    //User operations
    USER_LIST_KEYPAIRS,
    USER_ADD_KEYPAIRS,
    USER_REMOVE_KEYPAIRS,
    
    //Project operations
    PROJECTS_LIST,
    PROJECT_LIST_FLAVORS,
    PROJECT_LIST_REGIONS,
    PROJECT_LIST_AVAILABILITY_ZONES,
    PROJECT_LIST_NETWORKS,
    
    //Instances operations
    INSTANCES_ADD_IP,
    INSTANCES_ADD_TAG,
    INSTANCES_HARD_REBOOT,
    INSTANCES_LAUNCH,
    INSTANCES_LOCK,
    INSTANCES_PAUSE,
    INSTANCES_REMOVE_IP,
    INSTANCES_REMOVE_TAG,
    INSTANCES_RESIZE,
    INSTANCES_RESUME,
    INSTANCES_REBUILD,
    INSTANCES_SHOW_CONSOLE,
    INSTANCES_SHOW_INFO,
    INSTANCES_SHOW_LOG,
    INSTANCES_SHUTDOWN,
    INSTANCES_SNAPSHOT,
    INSTANCES_SOFT_REBOOT,
    INSTANCES_SUSPEND,
    INSTANCES_TERMINATE,
    INSTANCES_UNLOCK,
    
    //Image operations
    IMAGES_LIST,
    IMAGES_SHOW_INFO,
    IMAGES_MODIFY,
    IMAGES_REMOVE
    
}
